spring: 
#  main: 
#    web-application-type: NONE
  datasource:
    mongodb:
      url: mongodb://trading:trading@localhost:27017
      database: trading
binance: 
  baseUrl: 
    websocket: wss://fstream.binance.com
    rest: https://fapi.binance.com
loggin: 
  config: classpath:log4j2.xml