spring: 
#  main: 
#    web-application-type: NONE
  datasource:
    mongodb:
      url: mongodb://trading:trading@localhost:27017
      database: trading
loggin: 
  config: classpath:log4j2.xml