spring: 
  main: 
    web-application-type: NONE
email: 
  recipient: test@qq.com
  smtp: 
    host: smtp.qq.com
    port: 25
  auth: 
    user: test@qq.com
    password: 12345678
binance: 
  baseUrl: 
    rest: https://fapi.binance.com
    websocket: wss://fstream.binancefuture.com
  pair: |
    BTCUSDT,ETHUSDT,DOGEUSDT,BNBUSDT,SOLUSDT,LINKUSDT,ZKUSDT,1000PEPEUSDT,ENSUSDT,
    XRPUSDT,LTCUSDT,BCHUSDT,FILUSDT,ZECUSDT,ADAUSDT,ETHFIUSDT,TONUSDT,1000BONKUSDT,
    DOTUSDT,MATICUSDT,OPUSDT,ENAUSDT,AIUSDT,XAIUSDT,ALTUSDT,AVAXUSDT,WIFUSDT,NEARUSDT,
    APTUSDT,ORDIUSDT,NOTUSDT,WLDUSDT,FTMUSDT,ARBUSDT,ONDOUSDT,MKRUSDT,LDOUSDT,ETCUSDT,
    TWTUSDT,SFPUSDT,UNIUSDT,ZROUSDT,IOUSDT,TIAUSDT,BNXUSDT,WUSDT,LPTUSDT,IDUSDT,HOOKUSDT,
    EDUUSDT,SANDUSDT,SAGAUSDT,AXSUSDT,APEUSDT,MASKUSDT,
loggin: 
  config: classpath:log4j2.xml