spring: 
#  main: 
#    web-application-type: NONE
  datasource:
    mongodb:
      url: mongodb://trading:trading%40cai@localhost:27017
      database: trading
google:
  recaptcha:
    secret: 6LfFqqgqAAAAAMp1-4MDjtlxAt75mZdtlwwxjgr7	
binance: 
  baseUrl: 
    websocket: wss://fstream.binance.com
    rest: https://fapi.binance.com
    websocketApi: wss://ws-fapi.binance.com/ws-fapi/v1
loggin: 
  config: classpath:log4j2.xml